# the location where the system dependent experiment config files are
"experiment_system_dependent_dir": '~/WORK/BerryPicker/cfg/experiment-config'
# the location where the experiment data is put
# the experiments's specific data will be _/className/runName
"experiment_data": '~/WORK/BerryPicker/data'
# the place where the external experiment/run stuff goes. Other ones can be used, but it is convenient to keep one referred from here
"experiment_external": '~/WORK/BerryPicker/data_external'

conv_vae:
  # Directory for the checkout of the CONV_VAE project 
  # https://github.com/julian-8897/Conv-VAE-PyTorch
  code_dir: '~/WORK/BerryPicker/src/Conv-VAE-PyTorch'
